### ISSUE TITLE
Recent Changes and new changes

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Dev-Team/Scratch-ConsoleBased-Extensions#8]
All the changes, redirecttoscratchproject.js was pretty much copy and paste, and I had to make some changes that should have been done in the first place (https://github.com/Scratch-Dev-Team/Scratch-ConsoleBased-Extensions/commit/36a503fd03be867b2536ba76e6fc5abe7273cd58#diff-3c445e62ae8dba31393b8060f3ccb62724ccf595162090b6d64d42465595e285)
I would also like to have admin, and be the only admin of this repo. 
And what happened to the title?

- [ ] Change back title/Make it work for both (adding on console may not work because of one of the bookmarklet code elements)

**Comment by Shluffy** [comment]
I don't think this is something to just close.

**Comment by Shluffy** [comment]
I am going to change it to have some both for the console and bookmarklets

**Comment by ZI-Youtuber** [comment]
what?

**Comment by Shluffy** [comment]
> what?

there is a part of the code that may make it not work. And I am making it so it can be both. So can the tile be Scratch Bookmarkelts and Console

**Comment by ZI-Youtuber** [comment]
nah bookmarkets is  not a good name

**Comment by Shluffy** [comment]
This is _Not_ a wontifx As I am fixing this so it works for both

**Comment by Shluffy** [comment]
> nah bookmarkets is not a good name

okay. still making it work for both

**Comment by ZI-Youtuber** [comment]
ok but close this issue now. Not much important you can work on that
